name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'yarn'

      - name: Install
        run: yarn install

      - name: Build
        run: |
          yarn version --no-git-tag-version --new-version ${{ github.ref_name }}
          yarn build

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          body_path: dist/changelog_${{ github.ref_name }}.md
          files: dist/automation-glance.js
